# Generated by Django 5.1.1 on 2024-09-17 22:53

import datetime
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de la Rifa')),
                ('raffle_date', models.DateField(verbose_name='Fecha de la Rifa')),
                ('prizes', tinymce.models.HTMLField()),
                ('ticket_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo por Boleto')),
                ('min_tickets', models.IntegerField(verbose_name='Mínimo de Boletos para Participar')),
                ('available_tickets', models.IntegerField(verbose_name='Boletos Disponibles')),
                ('winner', tinymce.models.HTMLField()),
                ('payment_info', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('in_progress', 'En progreso'), ('finished', 'Finalizada')], default='in_progress', max_length=12, verbose_name='Estado de la Rifa')),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
                'db_table': 'raffle',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('identity_card', models.CharField(max_length=20, verbose_name='Cédula de Identidad')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Número de Teléfono')),
                ('tickets_purchased', models.IntegerField(verbose_name='Número de Boletos Comprados')),
                ('assigned_numbers', models.CharField(blank=True, max_length=255, null=True, verbose_name='Números Asignados')),
                ('payment_date', models.DateField(default=datetime.datetime.now, verbose_name='Fecha del Pago')),
                ('payment_reference', models.CharField(max_length=100, verbose_name='Referencia del Pago')),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='payments/', verbose_name='Captura del Pago')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Pago Confirmado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Confirmación'), ('confirmed', 'Confirmado')], default='pending', max_length=10, verbose_name='Estado del Pago')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='raffles.raffle')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'db_table': 'participant',
            },
        ),
    ]
