# Generated by Django 5.1.1 on 2024-09-17 23:10

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='winner',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Ganadores de la Rifa'),
        ),
    ]
