# Generated by Django 5.1.1 on 2024-09-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0002_alter_raffle_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='currency_type',
            field=models.CharField(choices=[('VEF', 'Bolívares (VEF)'), ('USD', 'Dólares (USD)')], default='VEF', max_length=3, verbose_name='Tipo de Moneda'),
        ),
    ]
