# Generated by Django 5.1.1 on 2024-09-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0003_raffle_currency_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='is_confirmed',
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado')], default='pending', max_length=10, verbose_name='Estado del Pago'),
        ),
    ]
