# Generated by Django 5.1.1 on 2024-09-26 14:21

import django.db.models.deletion
import raffles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0004_remove_participant_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to=raffles.models.payments_picture_path, verbose_name='Captura del Pago'),
        ),
        migrations.CreateModel(
            name='RafflePrizeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prizes/')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del premio')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_images', to='raffles.raffle')),
            ],
            options={
                'verbose_name': 'Imagen de premio',
                'verbose_name_plural': 'Imagenes de los premios',
                'db_table': 'prize_image',
            },
            bases=(models.Model, raffles.models.ImageManagementMixin),
        ),
    ]
