# Generated by Django 5.1.1 on 2024-09-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0006_remove_raffleprizeimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='assigned_numbers',
            field=models.TextField(verbose_name='Números Asignados'),
        ),
    ]
