# Generated by Django 5.1.1 on 2024-09-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0007_alter_participant_assigned_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='assigned_numbers',
            field=models.TextField(blank=True, null=True, verbose_name='Números Asignados'),
        ),
    ]
