# Generated by Django 5.1.1 on 2024-09-30 21:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0008_alter_participant_assigned_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
