# Generated by Django 5.1.1 on 2024-09-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0009_raffle_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='payment_reference',
            field=models.CharField(max_length=30, verbose_name='Referencia del Pago'),
        ),
    ]
