# Generated by Django 5.1.1 on 2024-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0011_alter_participant_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='identity_card',
            field=models.CharField(max_length=15, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='payment_reference',
            field=models.IntegerField(max_length=15, unique=True, verbose_name='Referencia del Pago'),
        ),
    ]
