# Generated by Django 5.1.1 on 2024-10-01 23:00

import raffles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0013_alter_participant_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='payment_receipt',
            field=models.ImageField(upload_to=raffles.models.payments_picture_path, verbose_name='Captura del Pago'),
        ),
    ]
