# Generated by Django 5.1.1 on 2024-10-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0014_alter_participant_payment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='min_tickets',
            field=models.CharField(max_length=15, verbose_name='Mínimo de Boletos para Participar'),
        ),
    ]
