# Generated by Django 5.1.1 on 2024-10-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0015_alter_raffle_min_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='payment_reference',
            field=models.CharField(max_length=15, unique=True, verbose_name='Referencia del Pago'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='min_tickets',
            field=models.IntegerField(verbose_name='Mínimo de Boletos para Participar'),
        ),
    ]
