# Generated by Django 5.1.1 on 2024-09-16 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'permissions': [('change_permissions_user', 'Puede gestionar permisos de usuario')], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
